### ISSUE TITLE
Sub-Task: Create Initial Branches

### ISSUE THREAD

**Issue by thejhh** [heusalagroup/planner#34]
* [ ] Create a 'main' branch which will hold the production-ready code.
* [ ] Set up a 'develop' branch for ongoing development.
* [ ] Optionally, create feature branches from 'develop' for individual features or tasks.
