### ISSUE TITLE
Task: Set up a version control repository (e.g., Git)

### ISSUE THREAD

**Issue by thejhh** [heusalagroup/planner#9]
### Objective 

To establish a robust version control system using Git that will manage and track all changes in the software project. This system will serve as the backbone for collaborative development, allowing multiple team members to work simultaneously on different aspects of the project without conflicting with each other's changes.

### Deliverables

* [x] A fully set-up Git repository on a chosen platform.
* [ ] Documentation and guidelines for using the repository.
* [ ] Integration with other project management tools (if applicable).
* [ ] Initial branches (main, develop, feature branches) created and ready for use.

### Notes

* Source code for the Planner will be in a private git submodule [heusalagroup/fi.hg.planner](https://github.com/heusalagroup/fi.hg.planner)
* Code will use [hyperifyio/io.hyperify.core](https://github.com/hyperifyio/io.hyperify.core) and related integrations, including the OpenAI API client.

### Sub-tasks

* [x] #31
* [ ] #32
* [ ] #33
* [ ] #34
* [ ] #35
* [ ] #36
